spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/prueba
    username: postgres
    password: renzo123

server.port: 8081

application:
  error:
    backend:
      create-employee: 'Error al guardar al Employee'
      update-employee: 'Error al actualizar al Employee'
      get-employee: 'Employee no encontrado'
  api:
    path: '/business/v1/employees'

logging:
  level:
    com.pe.relari.employee: TRACE